### ISSUE TITLE
Small rust example?

### ISSUE THREAD

**Issue by thomasaarholt** [jinlow/forust#15]
Hiya, and thanks for creating forust!
I've been learning Rust and playing with the [polars](https://github.com/pola-rs/polars) library (Dataframe library in rust), with the intention of building a pure-rust ML-pipeline.

I was wondering if you could write a small Rust Titanic code example on how to use Forust, equivalent to the Python one in the Github Readme? It would be nice to have in the Readme as well.

The 44KB Titanic data is available here:
https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv

**Comment by jinlow** [comment]
Hi @thomasaarholt, Absolutely!
This is something I have been meaning to use for a while, but haven’t gotten around to. But I should be able to add an example in the next few days!

**Comment by jinlow** [comment]
Apologies for the slow response on this, finally added a small self contained rust example [here](https://github.com/jinlow/forust/blob/main/rs-example.md). Also working on docs, where you will be able to switch between python and rust code, as all of the python methods are nearly an exact pass-through of the rust code.
