### ISSUE TITLE
Add early stopping rounds

### ISSUE THREAD

**Issue by jinlow** [jinlow/forust#18]
Right now the model just trains until it has reached the requested iterations, we should consider adding an `early_stopping_rounds` parameter. Although this get's a little cumbersome because then you need to provide an eval dataset, and additionally, we would need to add a bunch of eval metrics.

**Comment by thomasaarholt** [comment]
Being able to train with an eval dataset for early stopping is a big + for me at least :) It's the main way to avoid overfitting :)

**Comment by jinlow** [comment]
Merged into main, will go out on next release.
