### ISSUE TITLE
add calc_init to objective trait

### ISSUE THREAD

**Issue by gravesee** [jinlow/forust#36]
R's gbm package calculates the starting value for each objective given the target array. A function could be added to the objective trait that calculates.

For example, from R's bernoulli objective we see the code for the sample log-odds.

```c++
{
        double dSum=0.0;
        for(i=0; i<cLength; i++)
        {
            dSum += adWeight[i]*adY[i];
            dTemp += adWeight[i];
        }
        dInitF = log(dSum/(dTemp-dSum));
    }
```

And for their gaussian objective:

```c++
for(i=0; i<cLength; i++)
        {
            dSum += adWeight[i]*adY[i];
            dTotalWeight += adWeight[i];
        }
        dInitF = dSum/dTotalWeight;
```

**Comment by jinlow** [comment]
Merged into main, will go out on next release
