### ISSUE TITLE
Add variable importance measures

### ISSUE THREAD

**Issue by jinlow** [jinlow/forust#37]
Look at the different variable importance measures supported by XGBoost and add those calculations to forust.

**Comment by gravesee** [comment]
This paper could be useful for implementing an unbiased feature importance measure

https://arxiv.org/pdf/2305.10696.pdf

**Comment by jinlow** [comment]
Basic feature importance measures have now been implanted (gain, cover, and weight). Closing this, and will open a separate ticket to keep track of the unbiased gain.
