### ISSUE TITLE
Missing test data

### ISSUE THREAD

**Issue by MathisWellmann** [jinlow/forust#44]
Many tests (10) fail due to missing data, for example `resources/contiguous_no_missing.csv` is required by the `test_bin_data` test.
Its important that this data is added to the repository or the tests must be changed.

**Comment by jinlow** [comment]
Hey @MathisWellmann,
All of the test data is generated via a script in the `scripts\` directory. To see how to set up your dev environment and run tests, please check out the [contributing guide](https://github.com/jinlow/forust/blob/main/CONTRIBUTING.md).  
Thanks :)

**Comment by jinlow** [comment]
Although, I see now I only mention this script in the “running python tests” section, I’ll adjust the contributing guide to call it out a prerequisite to running any tests.

**Comment by MathisWellmann** [comment]
Cool thanks for the update
