### ISSUE TITLE
[Bug] Issue loading model trained in rust from python

### ISSUE THREAD

**Issue by The-Mr-L** [jinlow/forust#94]
Hi :) just a quick  heads up, I have not had the time yet to troubleshoot it , but I can without any problems train a model from python and load it from both python and rust but the trained model from rust can only be loaded from rust.  well the error is just a panic like this "PanicException: called `Option::unwrap()` on a `None` value" .  I will report back if I find the problem

**Comment by The-Mr-L** [comment]
btw the model setup is like so 
```
  let mut model = GradientBooster::default()
        .set_iterations(151)
        .set_objective_type(forust_ml::objective::ObjectiveType::LogLoss)
        .set_learning_rate(0.01)
        .set_max_depth(5)
        .set_gamma(0.)
        .set_initialize_base_score(false)
        .set_base_score(0.5)
        .set_min_leaf_weight(1.)
        .set_l2(1.);
    model.fit_unweighted(&matrix, &y, None)?;
    model.save_booster("./model.json")?;
```

**Comment by jinlow** [comment]
Thanks for reporting this! I see the problem, will close this when the fix is released.

**Comment by jinlow** [comment]
Please try again with version 0.4.5.

**Comment by The-Mr-L** [comment]
it works now :) thanks !
