### ISSUE TITLE
Default value for l2

### ISSUE THREAD

**Issue by deadsoul44** [jinlow/forust#97]
Default value for l2 reg should be 0.0

https://lightgbm.readthedocs.io/en/latest/Parameters.html#lambda_l2

**Comment by jinlow** [comment]
In the [XGBoost docs](https://xgboost.readthedocs.io/en/stable/parameter.html#parameters-for-tree-booster), reg_lambda defaults to 1.0, so I think it's OK to also default to 1 in this library.

**Comment by jinlow** [comment]
Closing, as I think it's OK to align with xgboost.
